# title: Pengyu Zhang 张鹏宇
logo: /assets/img/headshot.jpg
# description: Knowledge Graph, Graph Neural Network
# show_downloads: true
theme: jekyll-theme-minimal

twitter: https://x.com/pengyu_z
google_scholar: https://scholar.google.com/citations?user=xH7mJ-0AAAAJ&hl=en
