# Site Settings
title: "Pengyu Zhang (张鹏宇)"
description: "A third-year Ph.D. student at the University of Amsterdam (UvA), focusing on Temporal Knowledge Graphs (TKGs)."
repository: "pengyu-zhang/pengyu-zhang.github.io"

# Site Author
author:
  name: "Pengyu Zhang (张鹏宇)"
  avatar: "/assets/img/headshot.jpg"
  bio: "Enhancing Temporal Knowledge Graphs (TKGs) to better capture the dynamic nature of real-world entities and their relationships over time."
  location: "Amsterdam, Netherlands"
  employer: "University of Amsterdam"
  email: "p.zhang@uva.nl"
  twitter: "pengyu_z"
  linkedin: "pengyuzhang03"
  googlescholar: "https://scholar.google.com/citations?user=xH7mJ-0AAAAJ&hl=en"
  github: "pengyu-zhang"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - vendor

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
